[package]
name = "atomx-macro"
version = "0.1.0"
authors = ["Peter Hahlweg"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.6", features = ["full", "extra-traits"] }
quote = "1.0.8"
log = "0.4.14"
case = "1.0.0"